# Generated by Django 4.1.7 on 2023-09-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyRecords', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
