# Generated by Django 4.1.7 on 2023-06-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hygeia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('brief_history', models.TextField()),
                ('symptoms_description', models.TextField()),
                ('drup_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygeia.drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
