# Generated by Django 4.1.7 on 2023-06-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=200)),
                ('digital_address', models.CharField(max_length=300)),
                ('registration_code', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_class', models.CharField(max_length=100)),
                ('general_description', models.TextField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygeia.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(upload_to='wopharm/drugs')),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('decription', models.CharField(max_length=200)),
                ('is_in_stock', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hygeia.drugcategory')),
            ],
        ),
    ]
