# Generated by Django 4.1.7 on 2023-08-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hygeia', '0003_drug_side_effect_alter_drug_image_precriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugcategory',
            options={'verbose_name_plural': 'Drug Categories'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'pharmacies'},
        ),
        migrations.AlterModelOptions(
            name='precriptions',
            options={'verbose_name_plural': 'prescriptions'},
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='decription',
            new_name='description',
        ),
    ]
